### ISSUE TITLE
Can't bind multiple textures

### ISSUE THREAD

**Issue by ajbeach2** [stackgl/gl-audio-analyser#1]
in this code, both of the unforms contain frequencys in the fragment shader. How do you bind multiple textures?

``` javascript
function render () {
  var width = gl.drawingBufferWidth
  var height = gl.drawingBufferHeight

  gl.viewport(0, 0, width, height)

  shader.bind()
  shader.uniforms.uWaveform = analyser.bindWaveform(0)
  shader.uniforms.uFft = analyser.bindFrequencies(1)
  shader.uniforms.uResolution = [width, height]

  triangle(gl)
}
```

**Comment by mattdesl** [comment]
Should be fixed in `1.0.1`, let me know if you run into any more issues. :+1:

**Comment by mattdesl** [comment]
Wait, nevermind. Let me do some more testing..

**Comment by mattdesl** [comment]
Ok, I think I fixed it now. Please test with `1.0.2`. :smile:

**Comment by hughsk** [comment]
Thanks for that fix @mattdesl, well spotted :D
